### ISSUE TITLE
Yarn Is not Correctly Detected on Windows

### ISSUE THREAD

**Issue by memchk** [brunch/deps-install#2]
Windows does not support using spawn for anything other than `.exe` files, unless the option {shell:true} is used. However, that is not supported for any node version `< 6.0.0`. [cross-spawn](https://www.npmjs.com/package/cross-spawn) is a drop-in replacement that is cross compatible across all node versions and platforms and would allow for this package to work properly.

Due to the above failure, yarn is not correctly detected. If the code also tested in the same way for npm, it will fail the same, it is **not** an issue with yarn, but the underlying child_process API.

**Comment by shvaikalesh** [comment]
Closed by #3
