### ISSUE TITLE
checkDeps fails to detect namespaced packages on Windows

### ISSUE THREAD

**Issue by jkruse** [brunch/deps-install#7]
On Windows the internally used `readdirp` will return entries with backslashes, which causes `readVersions` to not detect namespaced packages at all.

If for example your package.json contains a dependency "@babel/runtime", and that dependency in installed in node_modules, then the "filterer" argument to `readVersions` will contain "@babel/runtime", and the "namespaces" argument will contain "@babel". This makes `readdirp` recurse into the "@babel" directory, but the entry that `directoryFilter` is called with has `entry.path = '@babel\runtime'`, so the filterer test fails, and the dependency is not returned.

This in turn will for example cause Brunch to re-run "npm install" every time when using babel on Windows.

**Comment by jkruse** [comment]
Pull request #8 will fix this problem. Hoping for a merge, release on NPM, and an updated release of Brunch using this new version. Let me know if I can be of assistance.

Thanks in advance.

**Comment by paulmillr** [comment]
0.2.2 should be automatically picked up by brunch. Thanks.
